INSERT INTO movies (title, year, genre, runtime) VALUES ('Forrest Gump', 1994, 'Drama, Romance', '142 min');
INSERT INTO creators (full_name) VALUES ('Robert Zemeckis');
INSERT INTO creators (full_name) VALUES ('Winston Groom');
INSERT INTO creators (full_name) VALUES ('Eric Roth');
INSERT INTO creators (full_name) VALUES ('Tom Hanks');
INSERT INTO creators (full_name) VALUES ('Robin Wright');
INSERT INTO creators (full_name) VALUES ('Gary Sinise');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (1, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (1, 2);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (1, 3);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (1, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (1, 5);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (1, 6);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Uncharted', 2022, 'Action, Adventure', '116 min');
INSERT INTO creators (full_name) VALUES ('Ruben Fleischer');
INSERT INTO creators (full_name) VALUES ('Rafe Judkins');
INSERT INTO creators (full_name) VALUES ('Art Marcum');
INSERT INTO creators (full_name) VALUES ('Matt Holloway');
INSERT INTO creators (full_name) VALUES ('Tom Holland');
INSERT INTO creators (full_name) VALUES ('Mark Wahlberg');
INSERT INTO creators (full_name) VALUES ('Antonio Banderas');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (2, 7);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (2, 8);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (2, 9);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (2, 10);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (2, 11);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (2, 12);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (2, 13);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Shawshank Redemption', 1994, 'Drama', '142 min');
INSERT INTO creators (full_name) VALUES ('Frank Darabont');
INSERT INTO creators (full_name) VALUES ('Stephen King');
INSERT INTO creators (full_name) VALUES ('Tim Robbins');
INSERT INTO creators (full_name) VALUES ('Morgan Freeman');
INSERT INTO creators (full_name) VALUES ('Bob Gunton');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (3, 14);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (3, 15);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (3, 14);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (3, 16);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (3, 17);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (3, 18);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode I - The Phantom Menace', 1999, 'Action, Adventure, Fantasy', '136 min');
INSERT INTO creators (full_name) VALUES ('George Lucas');
INSERT INTO creators (full_name) VALUES ('Ewan McGregor');
INSERT INTO creators (full_name) VALUES ('Liam Neeson');
INSERT INTO creators (full_name) VALUES ('Natalie Portman');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (4, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (4, 19);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (4, 20);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (4, 21);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (4, 22);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode II - Attack of the Clones', 2002, 'Action, Adventure, Fantasy', '142 min');
INSERT INTO creators (full_name) VALUES ('Jonathan Hales');
INSERT INTO creators (full_name) VALUES ('John Ostrander');
INSERT INTO creators (full_name) VALUES ('Hayden Christensen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (5, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (5, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (5, 23);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (5, 24);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (5, 25);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (5, 22);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (5, 20);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode III - Revenge of the Sith', 2005, 'Action, Adventure, Fantasy', '140 min');
INSERT INTO creators (full_name) VALUES ('Jan Duursema');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (6, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (6, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (6, 24);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (6, 26);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (6, 25);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (6, 22);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (6, 20);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars', 1977, 'Action, Adventure, Fantasy', '121 min');
INSERT INTO creators (full_name) VALUES ('Mark Hamill');
INSERT INTO creators (full_name) VALUES ('Harrison Ford');
INSERT INTO creators (full_name) VALUES ('Carrie Fisher');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (7, 19);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (7, 19);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (7, 27);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (7, 28);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (7, 29);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode V - The Empire Strikes Back', 1980, 'Action, Adventure, Fantasy', '124 min');
INSERT INTO creators (full_name) VALUES ('Irvin Kershner');
INSERT INTO creators (full_name) VALUES ('Leigh Brackett');
INSERT INTO creators (full_name) VALUES ('Lawrence Kasdan');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (8, 30);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (8, 31);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (8, 32);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (8, 19);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (8, 27);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (8, 28);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (8, 29);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode VI - Return of the Jedi', 1983, 'Action, Adventure, Fantasy', '131 min');
INSERT INTO creators (full_name) VALUES ('Richard Marquand');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (9, 33);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (9, 32);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (9, 19);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (9, 27);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (9, 28);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (9, 29);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode VII - The Force Awakens', 2015, 'Action, Adventure, Sci-Fi', '138 min');
INSERT INTO creators (full_name) VALUES ('J.J. Abrams');
INSERT INTO creators (full_name) VALUES ('Michael Arndt');
INSERT INTO creators (full_name) VALUES ('Daisy Ridley');
INSERT INTO creators (full_name) VALUES ('John Boyega');
INSERT INTO creators (full_name) VALUES ('Oscar Isaac');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (10, 34);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (10, 32);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (10, 34);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (10, 35);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (10, 36);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (10, 37);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (10, 38);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode VIII - The Last Jedi', 2017, 'Action, Adventure, Fantasy', '152 min');
INSERT INTO creators (full_name) VALUES ('Rian Johnson');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (11, 39);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (11, 39);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (11, 19);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (11, 36);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (11, 37);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (11, 27);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Star Wars: Episode IX - The Rise of Skywalker', 2019, 'Action, Adventure, Fantasy', '141 min');
INSERT INTO creators (full_name) VALUES ('Chris Terrio');
INSERT INTO creators (full_name) VALUES ('Derek Connolly');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (12, 34);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (12, 40);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (12, 34);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (12, 41);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (12, 36);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (12, 37);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (12, 38);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Action, Adventure, Drama', '178 min');
INSERT INTO creators (full_name) VALUES ('Peter Jackson');
INSERT INTO creators (full_name) VALUES ('J.R.R. Tolkien');
INSERT INTO creators (full_name) VALUES ('Fran Walsh');
INSERT INTO creators (full_name) VALUES ('Philippa Boyens');
INSERT INTO creators (full_name) VALUES ('Elijah Wood');
INSERT INTO creators (full_name) VALUES ('Ian McKellen');
INSERT INTO creators (full_name) VALUES ('Orlando Bloom');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (13, 42);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (13, 43);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (13, 44);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (13, 45);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (13, 46);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (13, 47);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (13, 48);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Lord of the Rings: The Two Towers', 2002, 'Action, Adventure, Drama', '179 min');
INSERT INTO creators (full_name) VALUES ('Viggo Mortensen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (14, 42);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (14, 43);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (14, 44);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (14, 45);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (14, 46);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (14, 47);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (14, 49);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Lord of the Rings: The Return of the King', 2003, 'Action, Adventure, Drama', '201 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (15, 42);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (15, 43);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (15, 44);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (15, 45);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (15, 46);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (15, 49);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (15, 47);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Rogue One: A Star Wars Story', 2016, 'Action, Adventure, Sci-Fi', '133 min');
INSERT INTO creators (full_name) VALUES ('Gareth Edwards');
INSERT INTO creators (full_name) VALUES ('Chris Weitz');
INSERT INTO creators (full_name) VALUES ('Tony Gilroy');
INSERT INTO creators (full_name) VALUES ('John Knoll');
INSERT INTO creators (full_name) VALUES ('Felicity Jones');
INSERT INTO creators (full_name) VALUES ('Diego Luna');
INSERT INTO creators (full_name) VALUES ('Alan Tudyk');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (16, 50);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (16, 51);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (16, 52);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (16, 53);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (16, 54);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (16, 55);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (16, 56);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Back to the Future', 1985, 'Adventure, Comedy, Sci-Fi', '116 min');
INSERT INTO creators (full_name) VALUES ('Bob Gale');
INSERT INTO creators (full_name) VALUES ('Michael J. Fox');
INSERT INTO creators (full_name) VALUES ('Christopher Lloyd');
INSERT INTO creators (full_name) VALUES ('Lea Thompson');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (17, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (17, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (17, 57);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (17, 58);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (17, 59);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (17, 60);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Back to the Future Part II', 1989, 'Adventure, Comedy, Sci-Fi', '108 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (18, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (18, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (18, 57);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (18, 58);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (18, 59);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (18, 60);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Back to the Future Part III', 1990, 'Adventure, Comedy, Sci-Fi', '118 min');
INSERT INTO creators (full_name) VALUES ('Mary Steenburgen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (19, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (19, 1);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (19, 57);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (19, 58);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (19, 59);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (19, 61);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Matrix', 1999, 'Action, Sci-Fi', '136 min');
INSERT INTO creators (full_name) VALUES ('Lana Wachowski');
INSERT INTO creators (full_name) VALUES ('Lilly Wachowski');
INSERT INTO creators (full_name) VALUES ('Keanu Reeves');
INSERT INTO creators (full_name) VALUES ('Laurence Fishburne');
INSERT INTO creators (full_name) VALUES ('Carrie-Anne Moss');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (20, 62);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (20, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (20, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (20, 62);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (20, 64);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (20, 65);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (20, 66);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Matrix Reloaded', 2003, 'Action, Sci-Fi', '138 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (21, 62);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (21, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (21, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (21, 62);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (21, 64);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (21, 65);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (21, 66);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Matrix Revolutions', 2003, 'Action, Sci-Fi', '129 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (22, 62);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (22, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (22, 63);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (22, 62);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (22, 64);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (22, 65);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (22, 66);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Pulp Fiction', 1994, 'Crime, Drama', '154 min');
INSERT INTO creators (full_name) VALUES ('Quentin Tarantino');
INSERT INTO creators (full_name) VALUES ('Roger Avary');
INSERT INTO creators (full_name) VALUES ('John Travolta');
INSERT INTO creators (full_name) VALUES ('Uma Thurman');
INSERT INTO creators (full_name) VALUES ('Samuel L. Jackson');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (23, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (23, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (23, 68);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (23, 69);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (23, 70);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (23, 71);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Inception', 2010, 'Action, Adventure, Sci-Fi', '148 min');
INSERT INTO creators (full_name) VALUES ('Christopher Nolan');
INSERT INTO creators (full_name) VALUES ('Leonardo DiCaprio');
INSERT INTO creators (full_name) VALUES ('Joseph Gordon-Levitt');
INSERT INTO creators (full_name) VALUES ('Elliot Page');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (24, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (24, 72);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (24, 73);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (24, 74);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (24, 75);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Interstellar', 2014, 'Adventure, Drama, Sci-Fi', '169 min');
INSERT INTO creators (full_name) VALUES ('Jonathan Nolan');
INSERT INTO creators (full_name) VALUES ('Matthew McConaughey');
INSERT INTO creators (full_name) VALUES ('Anne Hathaway');
INSERT INTO creators (full_name) VALUES ('Jessica Chastain');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (25, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (25, 76);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (25, 72);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (25, 77);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (25, 78);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (25, 79);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Dark Knight', 2008, 'Action, Crime, Drama', '152 min');
INSERT INTO creators (full_name) VALUES ('David S. Goyer');
INSERT INTO creators (full_name) VALUES ('Christian Bale');
INSERT INTO creators (full_name) VALUES ('Heath Ledger');
INSERT INTO creators (full_name) VALUES ('Aaron Eckhart');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (26, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (26, 76);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (26, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (26, 80);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (26, 81);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (26, 82);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (26, 83);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Joker', 2019, 'Crime, Drama, Thriller', '122 min');
INSERT INTO creators (full_name) VALUES ('Todd Phillips');
INSERT INTO creators (full_name) VALUES ('Scott Silver');
INSERT INTO creators (full_name) VALUES ('Bob Kane');
INSERT INTO creators (full_name) VALUES ('Joaquin Phoenix');
INSERT INTO creators (full_name) VALUES ('Robert De Niro');
INSERT INTO creators (full_name) VALUES ('Zazie Beetz');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (27, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (27, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (27, 85);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (27, 86);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (27, 87);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (27, 88);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (27, 89);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Wolf of Wall Street', 2013, 'Biography, Comedy, Crime', '180 min');
INSERT INTO creators (full_name) VALUES ('Martin Scorsese');
INSERT INTO creators (full_name) VALUES ('Terence Winter');
INSERT INTO creators (full_name) VALUES ('Jordan Belfort');
INSERT INTO creators (full_name) VALUES ('Jonah Hill');
INSERT INTO creators (full_name) VALUES ('Margot Robbie');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (28, 90);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (28, 91);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (28, 92);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (28, 73);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (28, 93);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (28, 94);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Django Unchained', 2012, 'Drama, Western', '165 min');
INSERT INTO creators (full_name) VALUES ('Jamie Foxx');
INSERT INTO creators (full_name) VALUES ('Christoph Waltz');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (29, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (29, 67);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (29, 95);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (29, 96);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (29, 73);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Shutter Island', 2010, 'Mystery, Thriller', '138 min');
INSERT INTO creators (full_name) VALUES ('Laeta Kalogridis');
INSERT INTO creators (full_name) VALUES ('Dennis Lehane');
INSERT INTO creators (full_name) VALUES ('Emily Mortimer');
INSERT INTO creators (full_name) VALUES ('Mark Ruffalo');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (30, 90);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (30, 97);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (30, 98);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (30, 73);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (30, 99);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (30, 100);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Godfather', 1972, 'Crime, Drama', '175 min');
INSERT INTO creators (full_name) VALUES ('Francis Ford Coppola');
INSERT INTO creators (full_name) VALUES ('Mario Puzo');
INSERT INTO creators (full_name) VALUES ('Marlon Brando');
INSERT INTO creators (full_name) VALUES ('Al Pacino');
INSERT INTO creators (full_name) VALUES ('James Caan');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (31, 101);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (31, 102);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (31, 101);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (31, 103);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (31, 104);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (31, 105);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Godfather: Part II', 1974, 'Crime, Drama', '202 min');
INSERT INTO creators (full_name) VALUES ('Robert Duvall');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (32, 101);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (32, 101);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (32, 102);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (32, 104);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (32, 88);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (32, 106);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Godfather: Part III', 1990, 'Crime, Drama', '162 min');
INSERT INTO creators (full_name) VALUES ('Diane Keaton');
INSERT INTO creators (full_name) VALUES ('Andy Garcia');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (33, 101);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (33, 102);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (33, 101);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (33, 104);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (33, 107);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (33, 108);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Inglourious Basterds', 2009, 'Adventure, Drama, War', '153 min');
INSERT INTO creators (full_name) VALUES ('Brad Pitt');
INSERT INTO creators (full_name) VALUES ('Diane Kruger');
INSERT INTO creators (full_name) VALUES ('Eli Roth');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (34, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (34, 67);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (34, 109);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (34, 110);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (34, 111);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Goodfellas', 1990, 'Biography, Crime, Drama', '145 min');
INSERT INTO creators (full_name) VALUES ('Nicholas Pileggi');
INSERT INTO creators (full_name) VALUES ('Ray Liotta');
INSERT INTO creators (full_name) VALUES ('Joe Pesci');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (35, 90);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (35, 112);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (35, 90);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (35, 88);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (35, 113);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (35, 114);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Reservoir Dogs', 1992, 'Crime, Drama, Thriller', '99 min');
INSERT INTO creators (full_name) VALUES ('Harvey Keitel');
INSERT INTO creators (full_name) VALUES ('Tim Roth');
INSERT INTO creators (full_name) VALUES ('Michael Madsen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (36, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (36, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (36, 68);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (36, 115);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (36, 116);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (36, 117);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Kill Bill: Vol. 1', 2003, 'Action, Crime, Drama', '111 min');
INSERT INTO creators (full_name) VALUES ('David Carradine');
INSERT INTO creators (full_name) VALUES ('Daryl Hannah');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (37, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (37, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (37, 70);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (37, 70);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (37, 118);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (37, 119);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Kill Bill: Vol. 2', 2004, 'Action, Crime, Thriller', '137 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (38, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (38, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (38, 70);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (38, 70);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (38, 118);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (38, 117);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Hateful Eight', 2015, 'Crime, Drama, Mystery', '168 min');
INSERT INTO creators (full_name) VALUES ('Kurt Russell');
INSERT INTO creators (full_name) VALUES ('Jennifer Jason Leigh');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (39, 67);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (39, 67);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (39, 71);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (39, 120);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (39, 121);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Scarface', 1983, 'Crime, Drama', '170 min');
INSERT INTO creators (full_name) VALUES ('Brian De Palma');
INSERT INTO creators (full_name) VALUES ('Oliver Stone');
INSERT INTO creators (full_name) VALUES ('Howard Hawks');
INSERT INTO creators (full_name) VALUES ('Ben Hecht');
INSERT INTO creators (full_name) VALUES ('Michelle Pfeiffer');
INSERT INTO creators (full_name) VALUES ('Steven Bauer');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (40, 122);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (40, 123);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (40, 124);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (40, 125);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (40, 104);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (40, 126);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (40, 127);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Taxi Driver', 1976, 'Crime, Drama', '114 min');
INSERT INTO creators (full_name) VALUES ('Paul Schrader');
INSERT INTO creators (full_name) VALUES ('Jodie Foster');
INSERT INTO creators (full_name) VALUES ('Cybill Shepherd');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (41, 90);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (41, 128);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (41, 88);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (41, 129);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (41, 130);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Usual Suspects', 1995, 'Crime, Drama, Mystery', '106 min');
INSERT INTO creators (full_name) VALUES ('Bryan Singer');
INSERT INTO creators (full_name) VALUES ('Christopher McQuarrie');
INSERT INTO creators (full_name) VALUES ('Kevin Spacey');
INSERT INTO creators (full_name) VALUES ('Gabriel Byrne');
INSERT INTO creators (full_name) VALUES ('Chazz Palminteri');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (42, 131);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (42, 132);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (42, 133);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (42, 134);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (42, 135);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Departed', 2006, 'Crime, Drama, Thriller', '151 min');
INSERT INTO creators (full_name) VALUES ('William Monahan');
INSERT INTO creators (full_name) VALUES ('Alan Mak');
INSERT INTO creators (full_name) VALUES ('Felix Chong');
INSERT INTO creators (full_name) VALUES ('Matt Damon');
INSERT INTO creators (full_name) VALUES ('Jack Nicholson');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (43, 90);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (43, 136);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (43, 137);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (43, 138);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (43, 73);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (43, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (43, 140);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Se7en', 1995, 'Crime, Drama, Mystery', '127 min');
INSERT INTO creators (full_name) VALUES ('David Fincher');
INSERT INTO creators (full_name) VALUES ('Andrew Kevin Walker');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (44, 141);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (44, 142);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (44, 17);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (44, 109);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (44, 133);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Memento', 2000, 'Mystery, Thriller', '113 min');
INSERT INTO creators (full_name) VALUES ('Guy Pearce');
INSERT INTO creators (full_name) VALUES ('Joe Pantoliano');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (45, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (45, 72);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (45, 76);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (45, 143);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (45, 66);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (45, 144);

INSERT INTO movies (title, year, genre, runtime) VALUES ('One Flew Over the Cuckoo''s Nest', 1975, 'Drama', '133 min');
INSERT INTO creators (full_name) VALUES ('Milos Forman');
INSERT INTO creators (full_name) VALUES ('Lawrence Hauben');
INSERT INTO creators (full_name) VALUES ('Bo Goldman');
INSERT INTO creators (full_name) VALUES ('Ken Kesey');
INSERT INTO creators (full_name) VALUES ('Louise Fletcher');
INSERT INTO creators (full_name) VALUES ('Michael Berryman');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (46, 145);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (46, 146);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (46, 147);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (46, 148);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (46, 140);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (46, 149);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (46, 150);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Spider-Man: Into the Spider-Verse', 2018, 'Animation, Action, Adventure', '117 min');
INSERT INTO creators (full_name) VALUES ('Bob Persichetti');
INSERT INTO creators (full_name) VALUES ('Peter Ramsey');
INSERT INTO creators (full_name) VALUES ('Rodney Rothman');
INSERT INTO creators (full_name) VALUES ('Phil Lord');
INSERT INTO creators (full_name) VALUES ('Shameik Moore');
INSERT INTO creators (full_name) VALUES ('Jake Johnson');
INSERT INTO creators (full_name) VALUES ('Hailee Steinfeld');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (47, 151);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (47, 152);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (47, 153);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (47, 154);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (47, 153);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (47, 155);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (47, 156);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (47, 157);

INSERT INTO movies (title, year, genre, runtime) VALUES ('WALL·E', 2008, 'Animation, Adventure, Family', '98 min');
INSERT INTO creators (full_name) VALUES ('Andrew Stanton');
INSERT INTO creators (full_name) VALUES ('Pete Docter');
INSERT INTO creators (full_name) VALUES ('Jim Reardon');
INSERT INTO creators (full_name) VALUES ('Ben Burtt');
INSERT INTO creators (full_name) VALUES ('Elissa Knight');
INSERT INTO creators (full_name) VALUES ('Jeff Garlin');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (48, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (48, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (48, 159);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (48, 160);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (48, 161);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (48, 162);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (48, 163);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Toy Story', 1995, 'Animation, Adventure, Comedy', '81 min');
INSERT INTO creators (full_name) VALUES ('John Lasseter');
INSERT INTO creators (full_name) VALUES ('Tim Allen');
INSERT INTO creators (full_name) VALUES ('Don Rickles');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (49, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (49, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (49, 159);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (49, 158);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (49, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (49, 165);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (49, 166);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Toy Story 2', 1999, 'Animation, Adventure, Comedy', '92 min');
INSERT INTO creators (full_name) VALUES ('Ash Brannon');
INSERT INTO creators (full_name) VALUES ('Lee Unkrich');
INSERT INTO creators (full_name) VALUES ('Joan Cusack');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (50, 164);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (50, 167);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (50, 168);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (50, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (50, 159);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (50, 167);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (50, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (50, 165);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (50, 169);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Toy Story 3', 2010, 'Animation, Adventure, Comedy', '103 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (51, 168);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (51, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (51, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (51, 168);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (51, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (51, 165);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (51, 169);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Toy Story 4', 2019, 'Animation, Adventure, Comedy', '100 min');
INSERT INTO creators (full_name) VALUES ('Josh Cooley');
INSERT INTO creators (full_name) VALUES ('Annie Potts');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (52, 170);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (52, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (52, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (52, 170);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (52, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (52, 165);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (52, 171);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Lion King', 1994, 'Animation, Adventure, Drama', '88 min');
INSERT INTO creators (full_name) VALUES ('Roger Allers');
INSERT INTO creators (full_name) VALUES ('Rob Minkoff');
INSERT INTO creators (full_name) VALUES ('Irene Mecchi');
INSERT INTO creators (full_name) VALUES ('Jonathan Roberts');
INSERT INTO creators (full_name) VALUES ('Linda Woolverton');
INSERT INTO creators (full_name) VALUES ('Matthew Broderick');
INSERT INTO creators (full_name) VALUES ('Jeremy Irons');
INSERT INTO creators (full_name) VALUES ('James Earl Jones');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (53, 172);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (53, 173);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (53, 174);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (53, 175);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (53, 176);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (53, 177);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (53, 178);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (53, 179);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Coco', 2017, 'Animation, Adventure, Comedy', '105 min');
INSERT INTO creators (full_name) VALUES ('Adrian Molina');
INSERT INTO creators (full_name) VALUES ('Jason Katz');
INSERT INTO creators (full_name) VALUES ('Matthew Aldrich');
INSERT INTO creators (full_name) VALUES ('Anthony Gonzalez');
INSERT INTO creators (full_name) VALUES ('Gael García Bernal');
INSERT INTO creators (full_name) VALUES ('Benjamin Bratt');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (54, 168);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (54, 180);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (54, 168);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (54, 181);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (54, 182);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (54, 183);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (54, 184);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (54, 185);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Up', 2009, 'Animation, Adventure, Comedy', '96 min');
INSERT INTO creators (full_name) VALUES ('Bob Peterson');
INSERT INTO creators (full_name) VALUES ('Tom McCarthy');
INSERT INTO creators (full_name) VALUES ('Edward Asner');
INSERT INTO creators (full_name) VALUES ('Jordan Nagai');
INSERT INTO creators (full_name) VALUES ('John Ratzenberger');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (55, 159);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (55, 186);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (55, 159);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (55, 186);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (55, 187);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (55, 188);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (55, 189);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (55, 190);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Finding Nemo', 2003, 'Animation, Adventure, Comedy', '100 min');
INSERT INTO creators (full_name) VALUES ('David Reynolds');
INSERT INTO creators (full_name) VALUES ('Albert Brooks');
INSERT INTO creators (full_name) VALUES ('Ellen DeGeneres');
INSERT INTO creators (full_name) VALUES ('Alexander Gould');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (56, 158);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (56, 168);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (56, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (56, 186);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (56, 191);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (56, 192);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (56, 193);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (56, 194);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Monsters, Inc.', 2001, 'Animation, Adventure, Comedy', '92 min');
INSERT INTO creators (full_name) VALUES ('David Silverman');
INSERT INTO creators (full_name) VALUES ('Jill Culton');
INSERT INTO creators (full_name) VALUES ('Jeff Pidgeon');
INSERT INTO creators (full_name) VALUES ('Billy Crystal');
INSERT INTO creators (full_name) VALUES ('John Goodman');
INSERT INTO creators (full_name) VALUES ('Mary Gibbs');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (57, 159);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (57, 195);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (57, 168);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (57, 159);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (57, 196);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (57, 197);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (57, 198);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (57, 199);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (57, 200);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Incredibles', 2004, 'Animation, Action, Adventure', '115 min');
INSERT INTO creators (full_name) VALUES ('Brad Bird');
INSERT INTO creators (full_name) VALUES ('Craig T. Nelson');
INSERT INTO creators (full_name) VALUES ('Holly Hunter');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (58, 201);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (58, 201);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (58, 202);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (58, 71);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (58, 203);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Spirited Away', 2001, 'Animation, Adventure, Family', '125 min');
INSERT INTO creators (full_name) VALUES ('Hayao Miyazaki');
INSERT INTO creators (full_name) VALUES ('Daveigh Chase');
INSERT INTO creators (full_name) VALUES ('Suzanne Pleshette');
INSERT INTO creators (full_name) VALUES ('Miyu Irino');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (59, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (59, 204);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (59, 205);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (59, 206);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (59, 207);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Howl''s Moving Castle', 2004, 'Animation, Adventure, Family', '119 min');
INSERT INTO creators (full_name) VALUES ('Diana Wynne Jones');
INSERT INTO creators (full_name) VALUES ('Chieko Baishô');
INSERT INTO creators (full_name) VALUES ('Takuya Kimura');
INSERT INTO creators (full_name) VALUES ('Tatsuya Gashûin');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (60, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (60, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (60, 208);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (60, 209);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (60, 210);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (60, 211);

INSERT INTO movies (title, year, genre, runtime) VALUES ('My Neighbor Totoro', 1988, 'Animation, Comedy, Family', '86 min');
INSERT INTO creators (full_name) VALUES ('Hitoshi Takagi');
INSERT INTO creators (full_name) VALUES ('Noriko Hidaka');
INSERT INTO creators (full_name) VALUES ('Chika Sakamoto');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (61, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (61, 204);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (61, 212);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (61, 213);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (61, 214);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Kiki''s Delivery Service', 1989, 'Animation, Family, Fantasy', '103 min');
INSERT INTO creators (full_name) VALUES ('Eiko Kadono');
INSERT INTO creators (full_name) VALUES ('Kirsten Dunst');
INSERT INTO creators (full_name) VALUES ('Minami Takayama');
INSERT INTO creators (full_name) VALUES ('Rei Sakuma');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (62, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (62, 215);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (62, 204);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (62, 216);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (62, 217);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (62, 218);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ponyo', 2008, 'Animation, Adventure, Comedy', '101 min');
INSERT INTO creators (full_name) VALUES ('Melissa Mathison');
INSERT INTO creators (full_name) VALUES ('Cate Blanchett');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (63, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (63, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (63, 219);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (63, 220);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (63, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (63, 21);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ocean''s Eleven', 2001, 'Crime, Thriller', '116 min');
INSERT INTO creators (full_name) VALUES ('Steven Soderbergh');
INSERT INTO creators (full_name) VALUES ('George Clayton Johnson');
INSERT INTO creators (full_name) VALUES ('Jack Golden Russell');
INSERT INTO creators (full_name) VALUES ('Harry Brown');
INSERT INTO creators (full_name) VALUES ('George Clooney');
INSERT INTO creators (full_name) VALUES ('Julia Roberts');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (64, 221);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (64, 222);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (64, 223);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (64, 224);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (64, 225);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (64, 109);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (64, 226);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ocean''s Twelve', 2004, 'Crime, Thriller', '125 min');
INSERT INTO creators (full_name) VALUES ('George Nolfi');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (65, 221);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (65, 227);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (65, 222);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (65, 223);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (65, 225);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (65, 109);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (65, 226);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ocean''s Thirteen', 2007, 'Crime, Thriller', '122 min');
INSERT INTO creators (full_name) VALUES ('Brian Koppelman');
INSERT INTO creators (full_name) VALUES ('David Levien');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (66, 221);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (66, 228);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (66, 229);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (66, 222);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (66, 225);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (66, 109);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (66, 139);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ocean''s Eleven', 1960, 'Comedy, Crime, Music', '127 min');
INSERT INTO creators (full_name) VALUES ('Lewis Milestone');
INSERT INTO creators (full_name) VALUES ('Charles Lederer');
INSERT INTO creators (full_name) VALUES ('Frank Sinatra');
INSERT INTO creators (full_name) VALUES ('Dean Martin');
INSERT INTO creators (full_name) VALUES ('Sammy Davis Jr.');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (67, 230);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (67, 224);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (67, 231);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (67, 222);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (67, 232);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (67, 233);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (67, 234);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Bourne Identity', 2002, 'Action, Mystery, Thriller', '119 min');
INSERT INTO creators (full_name) VALUES ('Doug Liman');
INSERT INTO creators (full_name) VALUES ('W. Blake Herron');
INSERT INTO creators (full_name) VALUES ('Robert Ludlum');
INSERT INTO creators (full_name) VALUES ('Franka Potente');
INSERT INTO creators (full_name) VALUES ('Chris Cooper');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (68, 235);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (68, 52);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (68, 236);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (68, 237);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (68, 238);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (68, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (68, 239);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Bourne Supremacy', 2004, 'Action, Mystery, Thriller', '108 min');
INSERT INTO creators (full_name) VALUES ('Paul Greengrass');
INSERT INTO creators (full_name) VALUES ('Joan Allen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (69, 240);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (69, 237);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (69, 52);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (69, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (69, 238);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (69, 241);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Bourne Ultimatum', 2007, 'Action, Mystery, Thriller', '115 min');
INSERT INTO creators (full_name) VALUES ('Scott Z. Burns');
INSERT INTO creators (full_name) VALUES ('Edgar Ramírez');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (70, 240);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (70, 52);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (70, 242);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (70, 227);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (70, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (70, 243);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (70, 241);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Hangover', 2009, 'Comedy', '100 min');
INSERT INTO creators (full_name) VALUES ('Jon Lucas');
INSERT INTO creators (full_name) VALUES ('Scott Moore');
INSERT INTO creators (full_name) VALUES ('Zach Galifianakis');
INSERT INTO creators (full_name) VALUES ('Bradley Cooper');
INSERT INTO creators (full_name) VALUES ('Justin Bartha');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (71, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (71, 244);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (71, 245);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (71, 246);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (71, 247);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (71, 248);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Hangover Part II', 2011, 'Comedy', '102 min');
INSERT INTO creators (full_name) VALUES ('Craig Mazin');
INSERT INTO creators (full_name) VALUES ('Scot Armstrong');
INSERT INTO creators (full_name) VALUES ('Ed Helms');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (72, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (72, 249);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (72, 250);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (72, 84);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (72, 247);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (72, 246);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (72, 251);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Hangover Part III', 2013, 'Comedy, Crime', '100 min');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (73, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (73, 84);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (73, 249);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (73, 244);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (73, 247);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (73, 246);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (73, 251);

INSERT INTO movies (title, year, genre, runtime) VALUES ('21 Jump Street', 2012, 'Action, Comedy, Crime', '109 min');
INSERT INTO creators (full_name) VALUES ('Christopher Miller');
INSERT INTO creators (full_name) VALUES ('Michael Bacall');
INSERT INTO creators (full_name) VALUES ('Patrick Hasburgh');
INSERT INTO creators (full_name) VALUES ('Channing Tatum');
INSERT INTO creators (full_name) VALUES ('Ice Cube');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (74, 154);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (74, 252);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (74, 253);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (74, 93);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (74, 254);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (74, 93);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (74, 255);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (74, 256);

INSERT INTO movies (title, year, genre, runtime) VALUES ('22 Jump Street', 2014, 'Action, Comedy, Crime', '112 min');
INSERT INTO creators (full_name) VALUES ('Oren Uziel');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (75, 154);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (75, 252);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (75, 253);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (75, 257);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (75, 153);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (75, 255);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (75, 93);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (75, 256);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Superbad', 2007, 'Comedy', '113 min');
INSERT INTO creators (full_name) VALUES ('Greg Mottola');
INSERT INTO creators (full_name) VALUES ('Seth Rogen');
INSERT INTO creators (full_name) VALUES ('Evan Goldberg');
INSERT INTO creators (full_name) VALUES ('Michael Cera');
INSERT INTO creators (full_name) VALUES ('Christopher Mintz-Plasse');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (76, 258);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (76, 259);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (76, 260);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (76, 261);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (76, 93);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (76, 262);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Pineapple Express', 2008, 'Action, Comedy, Crime', '111 min');
INSERT INTO creators (full_name) VALUES ('David Gordon Green');
INSERT INTO creators (full_name) VALUES ('Judd Apatow');
INSERT INTO creators (full_name) VALUES ('James Franco');
INSERT INTO creators (full_name) VALUES ('Gary Cole');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (77, 263);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (77, 259);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (77, 260);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (77, 264);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (77, 259);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (77, 265);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (77, 266);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Interview', 2014, 'Action, Adventure, Comedy', '112 min');
INSERT INTO creators (full_name) VALUES ('Dan Sterling');
INSERT INTO creators (full_name) VALUES ('Randall Park');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (78, 260);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (78, 259);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (78, 267);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (78, 259);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (78, 260);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (78, 265);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (78, 259);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (78, 268);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Step Brothers', 2008, 'Comedy', '98 min');
INSERT INTO creators (full_name) VALUES ('Adam McKay');
INSERT INTO creators (full_name) VALUES ('Will Ferrell');
INSERT INTO creators (full_name) VALUES ('John C. Reilly');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (79, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (79, 270);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (79, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (79, 271);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (79, 270);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (79, 271);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (79, 61);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Anchorman: The Legend of Ron Burgundy', 2004, 'Comedy', '94 min');
INSERT INTO creators (full_name) VALUES ('Christina Applegate');
INSERT INTO creators (full_name) VALUES ('Steve Carell');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (80, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (80, 270);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (80, 269);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (80, 270);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (80, 272);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (80, 273);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Talladega Nights: The Ballad of Ricky Bobby', 2006, 'Comedy, Sport', '108 min');
INSERT INTO creators (full_name) VALUES ('Sacha Baron Cohen');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (81, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (81, 270);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (81, 269);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (81, 270);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (81, 271);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (81, 274);

INSERT INTO movies (title, year, genre, runtime) VALUES ('The Other Guys', 2010, 'Action, Comedy, Crime', '107 min');
INSERT INTO creators (full_name) VALUES ('Chris Henchy');
INSERT INTO creators (full_name) VALUES ('Derek Jeter');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (82, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (82, 269);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (82, 275);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (82, 270);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (82, 12);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (82, 276);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Saving Private Ryan', 1998, 'Drama, War', '169 min');
INSERT INTO creators (full_name) VALUES ('Steven Spielberg');
INSERT INTO creators (full_name) VALUES ('Robert Rodat');
INSERT INTO creators (full_name) VALUES ('Tom Sizemore');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (83, 277);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (83, 278);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (83, 4);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (83, 139);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (83, 279);

INSERT INTO movies (title, year, genre, runtime) VALUES ('From Up on Poppy Hill', 2011, 'Animation, Comedy, Drama', '91 min');
INSERT INTO creators (full_name) VALUES ('Gorô Miyazaki');
INSERT INTO creators (full_name) VALUES ('Tetsurô Sayama');
INSERT INTO creators (full_name) VALUES ('Keiko Niwa');
INSERT INTO creators (full_name) VALUES ('Sarah Bolger');
INSERT INTO creators (full_name) VALUES ('Chris Noth');
INSERT INTO creators (full_name) VALUES ('Anton Yelchin');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (84, 280);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (84, 281);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (84, 204);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (84, 282);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (84, 283);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (84, 284);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (84, 285);

INSERT INTO movies (title, year, genre, runtime) VALUES ('8 Mile', 2002, 'Drama, Music', '110 min');
INSERT INTO creators (full_name) VALUES ('Curtis Hanson');
INSERT INTO creators (full_name) VALUES ('Eminem');
INSERT INTO creators (full_name) VALUES ('Brittany Murphy');
INSERT INTO creators (full_name) VALUES ('Kim Basinger');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (85, 286);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (85, 85);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (85, 287);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (85, 288);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (85, 289);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Madagascar', 2005, 'Animation, Adventure, Comedy', '86 min');
INSERT INTO creators (full_name) VALUES ('Eric Darnell');
INSERT INTO creators (full_name) VALUES ('Tom McGrath');
INSERT INTO creators (full_name) VALUES ('Mark Burton');
INSERT INTO creators (full_name) VALUES ('Billy Frolick');
INSERT INTO creators (full_name) VALUES ('Chris Rock');
INSERT INTO creators (full_name) VALUES ('Ben Stiller');
INSERT INTO creators (full_name) VALUES ('David Schwimmer');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (86, 290);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (86, 291);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (86, 292);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (86, 293);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (86, 290);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (86, 294);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (86, 295);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (86, 296);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Ratatouille', 2007, 'Animation, Adventure, Comedy', '111 min');
INSERT INTO creators (full_name) VALUES ('Jan Pinkava');
INSERT INTO creators (full_name) VALUES ('Jim Capobianco');
INSERT INTO creators (full_name) VALUES ('Brad Garrett');
INSERT INTO creators (full_name) VALUES ('Lou Romano');
INSERT INTO creators (full_name) VALUES ('Patton Oswalt');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (87, 201);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (87, 297);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (87, 201);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (87, 297);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (87, 298);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (87, 299);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (87, 300);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (87, 301);

INSERT INTO movies (title, year, genre, runtime) VALUES ('A Bug''s Life', 1998, 'Animation, Adventure, Comedy', '95 min');
INSERT INTO creators (full_name) VALUES ('Joe Ranft');
INSERT INTO creators (full_name) VALUES ('Dave Foley');
INSERT INTO creators (full_name) VALUES ('Julia Louis-Dreyfus');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (88, 164);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (88, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (88, 164);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (88, 158);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (88, 302);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (88, 133);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (88, 303);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (88, 304);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Tarzan', 1999, 'Animation, Adventure, Comedy', '88 min');
INSERT INTO creators (full_name) VALUES ('Chris Buck');
INSERT INTO creators (full_name) VALUES ('Kevin Lima');
INSERT INTO creators (full_name) VALUES ('Tab Murphy');
INSERT INTO creators (full_name) VALUES ('Bob Tzudiker');
INSERT INTO creators (full_name) VALUES ('Noni White');
INSERT INTO creators (full_name) VALUES ('Tony Goldwyn');
INSERT INTO creators (full_name) VALUES ('Minnie Driver');
INSERT INTO creators (full_name) VALUES ('Brian Blessed');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (89, 305);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (89, 306);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (89, 307);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (89, 308);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (89, 309);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (89, 310);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (89, 311);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (89, 312);

INSERT INTO movies (title, year, genre, runtime) VALUES ('Antz', 1998, 'Animation, Adventure, Comedy', '83 min');
INSERT INTO creators (full_name) VALUES ('Tim Johnson');
INSERT INTO creators (full_name) VALUES ('Todd Alcott');
INSERT INTO creators (full_name) VALUES ('Paul Weitz');
INSERT INTO creators (full_name) VALUES ('Woody Allen');
INSERT INTO creators (full_name) VALUES ('Sharon Stone');
INSERT INTO creators (full_name) VALUES ('Gene Hackman');
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (90, 290);
INSERT INTO movies_directed_by(movie_id, creator_id) VALUES (90, 313);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (90, 314);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (90, 51);
INSERT INTO movies_written_by(movie_id, creator_id) VALUES (90, 315);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (90, 316);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (90, 317);
INSERT INTO movies_acted_by(movie_id, creator_id) VALUES (90, 318);

